language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
notifications:
  email:
    recipients:
      - 12pm30@queensu.ca
#      - 12maw9@queensu.ca
      - 12ccyf@queensu.ca
    on_success: change # default: change
    on_failure: always # default: always
